language: ruby
arch:
  - amd64
  - ppc64le
before_install: gem install bundler
cache: bundler
rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
jobs:
  allow_failures:
    - rvm: ruby-head
# ppc64le support code
    - rvm: ruby-head
      arch: ppc64le
      
